# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Start Spring Boot Application
      run: |
        nohup java -jar target/resilient-sse-stream-0.0.1-SNAPSHOT.jar &
        sleep 10
        
    - name: Test SSE Endpoint
      run: |
        response=$(curl -N -H "Accept:text/event-stream" "http://localhost:8080/api/chat/stream?query=hello")
        echo "Response: $response"
        if [[ "$response" == *"[DONE]"* ]]; then
          echo "✅ SSE Test Passed"
        else
          echo "❌ SSE Test Failed"
          exit 1
        fi        
