# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Start Spring Boot Application
      run: |
        nohup java -jar target/resilient-sse-stream-0.0.1-SNAPSHOT.jar &
        sleep 10
        
    - name: Test SSE Endpoint
      run: |
        response=$(curl -N -H "Accept:text/event-stream" "http://localhost:8080/api/chat/stream?query=hello")
        echo "Response: $response"
        if [[ "$response" == *"[DONE]"* ]]; then
          echo "✅ SSE Test Passed"
        else
          echo "❌ SSE Test Failed"
          exit 1
        fi        
